name: example
description: A simple example app for the sliding_up_panel package.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  sliding_up_panel:
    path: ../

  flutter_map: ^1.1.0
  latlong: ^0.6.1
  cached_network_image: ^3.2.1

  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true